List<Map<String, String>> imageList = [
  {"file": "VVG-1.jpg", "name": "Le Pont de Langlois à Arles aux Lavandières", "categ": "Van Gogh"},
  {"file": "VVG-2.jpg", "name": "Terrasse de café de nuit", "categ": "Van Gogh"},
  {"file": "VVG-3.jpg", "name": "Les tournesols", "categ": "Van Gogh"},
  {"file": "VVG-4.jpg", "name": "Les Iris", "categ": "Van Gogh"},
  {"file": "VVG-5.jpg", "name": "Champ de blé avec cyprès", "categ": "Van Gogh"},
  {"file": "VVG-6.jpg", "name": "Chambre de Van Gogh", "categ": "Van Gogh"},
  {"file": "VVG-7.jpg", "name": "Barques sur la plage aux Saintes-Maries", "categ": "Van Gogh"},
  {"file": "VVG-8.jpg", "name": "La Meridienne ou La Sieste", "categ": "Van Gogh"},
  {"file": "VVG-9.jpg", "name": "Crâne d'homme avec cigarette", "categ": "Van Gogh"},
  {"file": "VVG-10.jpg", "name": "L'église d'Auvers-sur-Oise", "categ": "Van Gogh"},
  {"file": "VVG-11.jpg", "name": "La chambre à coucher à Arles", "categ": "Van Gogh"},
  {"file": "VVG-12.jpg", "name": "Chaumes de Cordeville à Auvers-sur-Oise", "categ": "Van Gogh"},
  {"file": "VVG-13.jpg", "name": "Deux peupliers sur la route des collines", "categ": "Van Gogh"},
  {"file": "VVG-14.jpg", "name": "Le bon Samaritain (d'après Delacroix)", "categ": "Van Gogh"},
  {"file": "VVG-15.jpg", "name": "La Pêche au Printemps, Pont de Clichy", "categ": "Van Gogh"},
  {"file": "VVG-16.jpg", "name": "Farmhouses at sunset", "categ": "Van Gogh"},
  {"file": "VVG-17.jpg", "name": "La lectrice de roman", "categ": "Van Gogh"},
  {"file": "VVG-18.jpg", "name": "Camps de Tziganes avec des voitures attelées", "categ": "Van Gogh"},
  {"file": "VVG-19.jpg", "name": "Le Faucheur", "categ": "Van Gogh"},
  {"file": "VVG-20.jpg", "name": "Maisons à Auvers", "categ": "Van Gogh"},
  {"file": "VVG-21.jpg", "name": "Les meules de foin", "categ": "Van Gogh"},
  {"file": "VVG-22.jpg", "name": "Portrait du Dr. Gachet", "categ": "Van Gogh"},
  {"file": "VVG-23.jpg", "name": "Portrait du facteur Joseph Roulin", "categ": "Van Gogh"},
  {"file": "VVG-24.jpg", "name": "Le peintre sur le chemin de travail", "categ": "Van Gogh"},
  {"file": "VVG-25.jpg", "name": "Auto-portrait avec oreille bandée et pipe", "categ": "Van Gogh"},

];
